version: '3.8'
services:
  skeeelo-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skeeelo-api
    entrypoint: sh -c 'yarn install --frozen-lockfile && yarn dev'
    networks:
      - skeeelo-network
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
      - /app/node_modules

networks:
  skeeelo-network:
